apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dyfc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dyfc
    app.kubernetes.io/part-of: tkrw-pr712-0075-0072-app
  name: devfile-sample-dyfc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dyfc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dyfc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-dyfc@sha256:f85435bdffbf4c974516cec543e3c8044f11ac3314235f22647b35ea2caf8af2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
